quiz_sets = [
    [   #SET 1
        {"text": "What are your interests?", "type": "text"},
        {"text": "What are your skills?", "type": "text"},
        {"text": "Which language is used to build Android apps?", "type": "mcq",
         "options": ["Python", "Java", "C++", "HTML"], "answer": "Java"},
        {"text": "What is the output of: print(2 + 3 * 2)?", "type": "mcq", "options": ["10", "8", "12", "6"],
         "answer": "8"},
        {"text": "Which shape completes the pattern? 2, 4, 8, ?", "type": "mcq", "options": ["10", "12", "16", "18"],
         "answer": "16"},
        {"text": "If all Bloops are Razzies and all Razzies are Lazzies, are all Bloops definitely Lazzies?",
         "type": "mcq", "options": ["Yes", "No", "Maybe", "Cannot Say"], "answer": "Yes"},
        {"text": "Find the missing number: 3, 9, 27, ?", "type": "mcq", "options": ["54", "72", "81", "90"],
         "answer": "81"},
        {"text": "You are given two ropes that each take exactly 60 minutes to burn, but burn non-linearly. How can you measure 45 minutes?",
            "type": "mcq", "options": ["Burn one fully and half another", "Burn one end of both ropes","Burn one rope both ends and the other one end", "Cut into 3 equal parts"],
            "answer": "Burn one rope both ends and the other one end"},
        {"text": "Solve: (12 + 18) / (6 - 3)", "type": "mcq", "options": ["10", "12", "6", "8"], "answer": "10"},
        {"text": "If angle A in triangle ABC is 90°, and angle B is 45°, what is angle C?", "type": "mcq",
         "options": ["30°", "45°", "60°", "90°"], "answer": "45°"}
    ],
    [  # Set 2
        {"text": "What are your interests?", "type": "text"},
        {"text": "What are your skills?", "type": "text"},
        {"text": "Which of these is not a programming language?", "type": "mcq",
         "options": ["Python", "HTML", "JavaScript", "C++"], "answer": "HTML"},
        {"text": "Which keyword is used to define a function in Python?", "type": "mcq",
         "options": ["def", "function", "define", "fun"], "answer": "def"},
        {"text": "Which figure completes the sequence: △, ◻, ◯, △, ◻, ?", "type": "mcq",
         "options": ["△", "◯", "◻", "□"], "answer": "◯"},
        {"text": "What comes next: ACE, BDF, ?", "type": "mcq", "options": ["EGI", "CDF", "CEG", "ADG"],
         "answer": "EGI"},
        {"text": "A train travels 60 km in 1 hour. How far will it go in 2.5 hours?", "type": "mcq",
         "options": ["120", "140", "150", "180"], "answer": "150"},
        {"text": "If 5x = 20, what is x?", "type": "mcq", "options": ["2", "3", "4", "5"], "answer": "4"},
        {"text": "What is 7² + 3²?", "type": "mcq", "options": ["49", "58", "59", "60"], "answer": "58"},
        {"text": "What is the square root of 81?", "type": "mcq", "options": ["7", "8", "9", "10"], "answer": "9"}

    ],
    [  # Set 3
        {"text": "What are your interests?", "type": "text"},
        {"text": "What are your skills?", "type": "text"},
        {"text": "Which of these is used for web development?", "type": "mcq",
         "options": ["Python", "HTML", "Java", "C++"], "answer": "HTML"},
        {"text": "What is the output of: print(5 * 6 / 2)?", "type": "mcq", "options": ["15", "12", "10", "18"],
         "answer": "15"},
        {"text": "What comes next in the series: 1, 4, 9, 16, ?", "type": "mcq", "options": ["25", "36", "30", "20"],
         "answer": "25"},
        {"text": "If all Wibbles are Zibbles, and all Zibbles are Wobbles, are all Wibbles definitely Wobbles?",
         "type": "mcq", "options": ["Yes", "No", "Maybe", "Cannot Say"], "answer": "Yes"},
        {"text": "What comes next in the pattern: 3, 6, 9, 12, ?", "type": "mcq", "options": ["15", "14", "16", "13"],
         "answer": "15"},
        {
            "text": "You have 3 candles. One lasts 5 hours, another 3 hours, and the last one 2 hours. How do you measure exactly 4 hours?",
            "type": "mcq", "options": ["Burn two candles simultaneously", "Burn one completely and another halfway",
                                       "Burn the shortest and longest candles", "Burn all three at once"],
            "answer": "Burn one completely and another halfway"},
        {"text": "What is the solution to: 7 * (5 + 3) - 6?", "type": "mcq", "options": ["52", "56", "54", "50"],
         "answer": "52"},
        {
            "text": "If the interior angles of a triangle sum up to 180°, and two angles are 70° and 50°, what is the third angle?",
            "type": "mcq", "options": ["60°", "55°", "65°", "75°"], "answer": "60°"}
    ],
    [  # Set 4
        {"text": "What are your interests?", "type": "text"},
        {"text": "What are your skills?", "type": "text"},
        {"text": "Which of these is a valid Python data type?", "type": "mcq",
         "options": ["List", "Array", "Object", "Set"], "answer": "List"},
        {"text": "What does the following code output: print('Hello ' + 'World')?", "type": "mcq",
         "options": ["HelloWorld", "Hello World", "Hello", "World"], "answer": "Hello World"},
        {"text": "Which number completes the series: 2, 4, 8, 16, ?", "type": "mcq",
         "options": ["18", "32", "24", "64"], "answer": "32"},
        {"text": "If all Apples are Berries and some Berries are Fruits, are all Apples definitely Fruits?",
         "type": "mcq", "options": ["Yes", "No", "Maybe", "Cannot Say"], "answer": "Maybe"},
        {"text": "If 10% of a number is 25, what is the number?", "type": "mcq", "options": ["250", "50", "200", "100"],
         "answer": "250"},
        {"text": "Which of the following is the odd one out? 5, 11, 17, 23, 31, 37, 41, 45", "type": "mcq",
         "options": ["5", "17", "45", "23"], "answer": "45"},
        {"text": "A store sells an item for $150 after giving a 25% discount. What was the original price?",
         "type": "mcq", "options": ["$200", "$175", "$250", "$300"], "answer": "$200"},
        {"text": "What is the perimeter of a square with side length 8 cm?", "type": "mcq",
         "options": ["16 cm", "32 cm", "24 cm", "64 cm"], "answer": "32 cm"}
    ],
    [  # Set 5
        {"text": "What are your interests?", "type": "text"},
        {"text": "What are your skills?", "type": "text"},
        {"text": "Which of these is used for front-end web development?", "type": "mcq",
         "options": ["Python", "CSS", "C++", "Java"], "answer": "CSS"},
        {"text": "What is the output of: print(10 / 2 + 3)?", "type": "mcq", "options": ["8", "7", "5", "6"],
         "answer": "8"},
        {"text": "What comes next in the series: 1, 1, 2, 3, 5, ?", "type": "mcq", "options": ["8", "7", "6", "9"],
         "answer": "8"},
        {"text": "If all Cats are Dogs and some Dogs are Pets, are all Cats definitely Pets?", "type": "mcq",
         "options": ["Yes", "No", "Maybe", "Cannot Say"], "answer": "Cannot Say"},
        {"text": "Which number completes the sequence: 2, 6, 12, 20, ?", "type": "mcq",
         "options": ["28", "30", "32", "35"], "answer": "30"},
        {"text": "You have a bucket with a hole in it. How do you fill the bucket with water?", "type": "mcq",
         "options": ["Fix the hole first", "Use another container", "Fill it with a spoon", "Use a different bucket"],
         "answer": "Fix the hole first"},
        {"text": "Solve: 15 - (3 * 2) + 5", "type": "mcq", "options": ["12", "10", "8", "6"], "answer": "12"},
        {"text": "In a right triangle, if one angle is 30°, what is the other non-right angle?", "type": "mcq",
         "options": ["45°", "60°", "90°", "75°"], "answer": "60°"}
    ],
    [  # Set 6
        {"text": "What are your interests?", "type": "text"},
        {"text": "What are your skills?", "type": "text"},
        {"text": "Which of these is used for creating mobile apps?", "type": "mcq",
         "options": ["Swift", "HTML", "Python", "Ruby"], "answer": "Swift"},
        {"text": "What is the output of: print(5 ** 2)?", "type": "mcq", "options": ["25", "10", "5", "50"],
         "answer": "25"},
        {"text": "What comes next in the series: 1, 4, 9, 16, ?", "type": "mcq", "options": ["24", "25", "36", "49"],
         "answer": "25"},
        {"text": "If all Bats are Bears and some Bears are Wolves, are all Bats definitely Wolves?", "type": "mcq",
         "options": ["Yes", "No", "Maybe", "Cannot Say"], "answer": "Cannot Say"},
        {"text": "What completes the pattern: 5, 10, 15, 20, ?", "type": "mcq", "options": ["25", "30", "35", "40"],
         "answer": "25"},
        {
            "text": "You have two boxes. One contains red balls and the other blue balls. How can you ensure that both boxes contain at least one red ball?",
            "type": "mcq",
            "options": ["Mix the balls together", "Take a red ball from one box", "Take a blue ball from one box",
                        "Use a third box"], "answer": "Take a red ball from one box"},
        {"text": "Solve: (8 * 6) / 4", "type": "mcq", "options": ["12", "10", "16", "14"], "answer": "12"},
        {"text": "If a circle has a radius of 7 cm, what is the area of the circle? (Use π ≈ 3.14)", "type": "mcq",
         "options": ["153.86 cm²", "153.94 cm²", "154.00 cm²", "150.00 cm²"], "answer": "153.86 cm²"}
    ],
    [  # Set 7
        {"text": "What are your interests?", "type": "text"},
        {"text": "What are your skills?", "type": "text"},
        {"text": "Which programming language is best known for machine learning?", "type": "mcq",
         "options": ["Python", "C", "Java", "Ruby"], "answer": "Python"},
        {"text": "What is the result of: print(4 * 3 + 2)?", "type": "mcq", "options": ["14", "15", "10", "12"],
         "answer": "14"},
        {"text": "Which number completes the sequence: 2, 5, 10, 17, ?", "type": "mcq",
         "options": ["26", "30", "35", "24"], "answer": "26"},
        {"text": "If all Trees are Plants, and some Plants are Flowers, can we conclude that all Trees are Flowers?",
         "type": "mcq", "options": ["Yes", "No", "Maybe", "Cannot Say"], "answer": "No"},
        {"text": "What is the next number in the series: 3, 6, 12, 24, ?", "type": "mcq",
         "options": ["48", "60", "72", "36"], "answer": "48"},
        {
            "text": "You have two light switches, and you can't see the lights. How can you determine which switch controls which light?",
            "type": "mcq", "options": ["Turn on one, wait, then turn on the second one", "Turn them both on at once",
                                       "Test them one by one", "Use a third person to check"],
            "answer": "Turn on one, wait, then turn on the second one"},
        {"text": "Solve: 3 + (8 / 4) * 2", "type": "mcq", "options": ["8", "10", "7", "6"], "answer": "7"},
        {"text": "What is the area of a triangle with a base of 10 cm and height of 5 cm?", "type": "mcq",
         "options": ["25 cm²", "50 cm²", "30 cm²", "35 cm²"], "answer": "25 cm²"}
    ],
    [  # Set 8
        {"text": "What are your interests?", "type": "text"},
        {"text": "What are your skills?", "type": "text"},
        {"text": "Which of these is commonly used for data analysis?", "type": "mcq",
         "options": ["Python", "Swift", "Go", "Perl"], "answer": "Python"},
        {"text": "What is the output of: print(9 - 3 * 2)?", "type": "mcq", "options": ["3", "9", "6", "0"],
         "answer": "3"},
        {"text": "What comes next in the sequence: 4, 9, 16, 25, ?", "type": "mcq", "options": ["36", "32", "30", "40"],
         "answer": "36"},
        {"text": "If all Pigs are Animals and all Animals are Mammals, are all Pigs definitely Mammals?", "type": "mcq",
         "options": ["Yes", "No", "Maybe", "Cannot Say"], "answer": "Yes"},
        {"text": "Which of the following is a valid Python syntax to print a message?", "type": "mcq",
         "options": ["print('Hello, world!')", "echo 'Hello, world!'", "console.log('Hello, world!')",
                     "printf('Hello, world!')"], "answer": "print('Hello, world!')"},
        {"text": "How many ways can you arrange 3 objects?", "type": "mcq", "options": ["6", "3", "9", "5"],
         "answer": "6"},
        {"text": "What is the next number in the sequence: 2, 4, 8, 16, ?", "type": "mcq",
         "options": ["32", "36", "24", "20"], "answer": "32"},
        {"text": "What is the perimeter of a rectangle with length 12 cm and width 5 cm?", "type": "mcq",
         "options": ["34 cm", "30 cm", "25 cm", "40 cm"], "answer": "34 cm"}
    ],
    [  # Set 9
        {"text": "What are your interests?", "type": "text"},
        {"text": "What are your skills?", "type": "text"},
        {"text": "Which language is primarily used for game development?", "type": "mcq",
         "options": ["Python", "C#", "Java", "Ruby"], "answer": "C#"},
        {"text": "What is the output of: print(10 // 3)?", "type": "mcq", "options": ["3", "3.33", "4", "2"],
         "answer": "3"},
        {"text": "Which number completes the series: 1, 1, 2, 6, 24, ?", "type": "mcq",
         "options": ["120", "36", "48", "72"], "answer": "120"},
        {"text": "If all Apples are Fruits and some Fruits are Red, can we conclude that all Apples are Red?",
         "type": "mcq", "options": ["Yes", "No", "Maybe", "Cannot Say"], "answer": "Cannot Say"},
        {"text": "What is the next number in the sequence: 1, 4, 9, 16, ?", "type": "mcq",
         "options": ["25", "30", "36", "40"], "answer": "25"},
        {
            "text": "You are in a room with two doors. One leads to freedom, the other leads to a trap. There are two guards, one always tells the truth and one always lies. You can ask one question to one guard. What do you ask?",
            "type": "mcq",
            "options": ["Which door leads to freedom?", "Which door leads to the trap?", "Can you tell me where I am?",
                        "What is your name?"], "answer": "Which door leads to freedom?"},
        {"text": "Solve: (12 + 4) / 4", "type": "mcq", "options": ["4", "6", "3", "5"], "answer": "4"},
        {"text": "If a square has an area of 49 cm², what is the length of each side?", "type": "mcq",
         "options": ["7 cm", "6 cm", "8 cm", "5 cm"], "answer": "7 cm"}
    ],
    [  # Set 10
        {"text": "What are your interests?", "type": "text"},
        {"text": "What are your skills?", "type": "text"},
        {"text": "Which language is often used for server-side scripting?", "type": "mcq",
         "options": ["PHP", "Java", "Python", "JavaScript"], "answer": "PHP"},
        {"text": "What is the output of: print(3 * (2 + 5))?", "type": "mcq", "options": ["21", "15", "18", "20"],
         "answer": "21"},
        {"text": "Which number completes the sequence: 2, 4, 8, 16, 32, ?", "type": "mcq",
         "options": ["64", "48", "40", "80"], "answer": "64"},
        {"text": "If all Dogs are Mammals and some Mammals are Animals, can we conclude that all Dogs are Animals?",
         "type": "mcq", "options": ["Yes", "No", "Maybe", "Cannot Say"], "answer": "Cannot Say"},
        {"text": "What is the next number in the sequence: 10, 20, 30, 40, ?", "type": "mcq",
         "options": ["50", "45", "60", "35"], "answer": "50"},
        {"text": "You have a 5-liter jug and a 3-liter jug. How do you measure exactly 4 liters of water?",
         "type": "mcq", "options": ["Fill the 5-liter jug and pour into the 3-liter jug", "Fill both jugs to the top",
                                    "Use a third jug", "Fill the 5-liter jug and discard the water"],
         "answer": "Fill the 5-liter jug and pour into the 3-liter jug"},
        {"text": "Solve: (15 * 2) / 5", "type": "mcq", "options": ["6", "5", "10", "12"], "answer": "6"},
        {"text": "What is the area of a circle with a radius of 7 cm? (Use π ≈ 3.14)", "type": "mcq",
         "options": ["153.94 cm²", "144 cm²", "160 cm²", "157.85 cm²"], "answer": "153.94 cm²"}
    ]

]
